### ISSUE TITLE
EVM Leaves are not relayed

### ISSUE THREAD

**Issue by nepoche** [webb-tools/relayer#239] opened 2022-08-02 15:18 UTC
#### Setup
`master` branch relayer (not relaying): https://github.com/webb-tools/relayer/pull/237
evm-localnet: https://github.com/webb-tools/evm-localnet
relayer (working): [8181c953](https://github.com/webb-tools/relayer/tree/8181c953f1019752fedde4dc41ced985c259f9c5)

#### Reproduce
Use the configuration in the linked PR for the relayer.

1) In the evm-localnet repo, run: `yarn start`.
2) wait for the deployments to finish ~block 94.
3) use the evm-localnet cli: `variable deposit on chain a`
4) view transactions submitted on-chain
5) start the relayer: `./target/release/webb-relayer -c config/development/evm-localnet/ -vvv`
6) Observe the relayer sees the leaves, but does not notify the signature bridge to relay roots.
7) switch to the relayer at the specified commit
8) start the relayer: `./target/release/webb-relayer -c config/development/evm-localnet/ -vvv`
9) Observe the relayer sees the leaves, and transactions for the relay are completed.

#### Other Information

https://user-images.githubusercontent.com/16654909/182410507-f0a01451-8995-4c58-aee7-2faf72cab069.mov

**Comment by shekohex** [comment] 2022-08-02 15:33
Duplicate of #204

**Closed** 2022-08-03 12:37 UTC
Labels: bug 🪲, p1 🟠, testing 🛠️, needs more info ℹ️
