### ISSUE TITLE
[SPEC] Refactor the Relayer codebase into smaller crates

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#69] opened 2022-01-06 18:28 UTC
### Motivation

The Relayer codebase started to get a bit bigger now, with different parts that are not entirely related to each other, between substrate & EVM, and any new system we are going to support in the future.

Besides that, the Webb Relayer is not that old dummy simple HTTP server that would just relay transactions blindly anymore, now it serves a critical part (most critical part in my opinion) is to bridge the transactions and watches for contracts cross-chains and do many other smart things.

### New Workspace

1. Webb Relayer Config (`wr-config` crate)
This will serve as the main part for just loading and hand-over the `WebbRelayerConfig`, it would be controlled by feature flags of what part of the system it supports for example ('evm', 'substrate', 'cosmos', ...etc)
2. Webb Relayer Database (`wr-db` crate)
This crate will contain all the traits and helpers for the database and stores (`QueueStore`, `LeavesStore`, ...etc). No Specific Impelemtation here, except for an in-memory database implementation provided by default.
3. Webb Relayer Database with Sled (`wr-db-sled` crate)
This would be an implementation of the traits provided by the `wr-db` crate over the sled.rs database, and then this crate would be included inside the `wr-db` crate behind a `sled` feature flag.
4. Webb Relayer Events Watcher (`wr-ewatcher`)
This is an Important crate, it will contain the `EventsWatcher` traits for (`evm`, `substrate`, ..etc) behind these feature flags, with the most robust default implementation for the events watchers for every system we support.
5. Webb Relayer EVM Events Watcher (`wr-evm-ewatcher`)
6. Webb Relayer Substrate Events Watcher (`wr-sub-ewatcher`)
Both of the above crates would use the traits from `wr-ewatcher` and implement it for different kinds of contract watchers like `Anchors` and `Bridges` also the pallets watchers like `DKGProposalsHandler`.
7. Webb Relayer HTTP Services (`wr-http-service`)
This one is pretty much simple since we are going to build it on top of [tower-rs](https://github.com/tower-rs/tower) where every transaction relayer is a simple service trait that we can implement and then plug in each service as needed, also this enables us to separate the services and separate smaller crates for different systems like EVM or substrate.

I would like also to remove the support from [`warp`](https://github.com/seanmonstar/warp) and start using [`axum`](https://github.com/tokio-rs/axum) instead, for better support from tower-rs and tokio runtime.

We could take the chance and transition from using WebSockets to [Server-Sent Event](https://en.wikipedia.org/wiki/Server-sent_events#:~:text=Server%2DSent%20Events%20(SSE),client%20connection%20has%20been%20established.)s over Http/2 for maximum performance.

8. Webb Relayer Test-probe (`wr-test-probe` crate)
An Important crate that will do a lot to help debug the Webb Relayer by leveraging the awesome [tracing](https://github.com/tokio-rs/tracing) crate that we already use, and by implementing our own custom [Subscriber/Collector](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/) to collect these data and exposing it in a more efficient and easy to analyze over say an HTTP service, that could be used to get and query the relayer state so it is easier to test.

8. Webb Relayer crate (`wr` crate).
This is like an umbrella crate where it wraps and exports the above crates under simplified names and modules (like re-export everything related to HTTP under `wr::http` module, everything for EVM under `wr::evm` module ...etc).
Again, this is a simple library, it would also contain helper async functions to kick-off the different services by default, this could **in the future** enable us to embed the relayer into other systems.
9. Webb Relayer binary (`webb-relayer` bin crate)
The last layer here, a binary over the `wa` crate, is a simple CLI that will read the config files and give them to the `wa` crate, and bootstrap the services, it shouldn't do much on its own tho.

### Workspace Diagram

![image](https://user-images.githubusercontent.com/14620076/149141020-7d4e6efa-5221-4f67-b0cf-3bd014f0a9f0.png)

**Comment by dutterbutter** [comment] 2022-07-28 19:40
@shekohex is this a duplicate of https://github.com/webb-tools/relayer/issues/212

**Comment by shekohex** [comment] 2022-07-29 02:39
No, it is not a duplicate,in fact you can consider #212 as a first step, but the ultimate goal is to refactor the Relayer in the future to look like the one defined by this SPEC here.

**Comment by salman01zp** [comment] 2022-11-01 10:38
closes in #289

**Closed by salman01zp** 2022-11-01 10:38 UTC
Labels: p2 🟡, spec 🆕, task ✔️
